In [56]:
import pandas
import matplotlib.pyplot as plt

data = pandas.read_csv("../report.csv")

In [57]:
data

,n_robots,algorithm,n_goals,n_goals_completed,n_goals_failed,distance_traveled,n_transfers,planning_time,n_planning_timeouts,postponements,replans,transfer_distance_traveled,n_conflicts,n_rr_conflicts,n_steps
0,1,namo,50.0,50.0,0.0,33590.564985,17.0,10.839305,0.0,0.0,50.0,1185.624475,0.0,0.0,2671.0
1,1,namo,50.0,50.0,0.0,49623.563382,25.0,19.521036,0.0,0.0,50.0,1415.330111,0.0,0.0,3883.0
2,1,namo,50.0,50.0,0.0,46001.222371,28.0,15.288761,0.0,0.0,50.0,1403.969724,0.0,0.0,3610.0
3,1,namo,50.0,49.0,1.0,26837.031720,26.0,16.167485,0.0,0.0,50.0,1736.543315,0.0,0.0,2260.0
4,1,namo,50.0,50.0,0.0,36400.584620,32.0,13.715717,0.0,0.0,50.0,1548.822542,0.0,0.0,2926.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3323,7,snamo_ncr,50.0,1.0,49.0,590.771645,0.0,105.313188,0.0,0.0,50.0,0.000000,49.0,49.0,107.0
3324,7,snamo_ncr,50.0,0.0,50.0,168.639610,0.0,158.234064,0.0,0.0,50.0,0.000000,50.0,50.0,63.0
3325,7,snamo_ncr,50.0,24.0,26.0,14823.141021,11.0,39.659353,0.0,0.0,50.0,1808.345249,26.0,25.0,1242.0
3326,7,snamo_ncr,50.0,3.0,47.0,484.705627,0.0,79.578303,0.0,0.0,50.0,0.000000,47.0,47.0,105.0
3327,7,snamo_ncr,50.0,2.0,48.0,1010.974046,2.0,89.098662,0.0,0.0,50.0,597.426409,48.0,47.0,142.0

In [58]:
avg = data.groupby(['n_robots','algorithm']).mean()

In [62]:
avg

                    n_goals  n_goals_completed  n_goals_failed  \
n_robots algorithm
1        namo          50.0          49.500000        0.500000
         namo_ncr      50.0          49.500000        0.500000
         namo_ndr      50.0          49.500000        0.500000
         snamo         50.0          49.050000        0.950000
         snamo_ncr     50.0          49.050000        0.950000
         snamo_ndr     50.0          49.050000        0.950000
2        namo          50.0          44.175000        5.825000
         namo_ncr      50.0          22.050000       27.950000
         namo_ndr      50.0          36.650000       13.350000
         snamo         50.0          44.925000        5.075000
         snamo_ncr     50.0          20.525000       29.475000
         snamo_ndr     50.0          37.825000       12.175000
3        namo          50.0          42.000000        8.000000
         namo_ncr      50.0          15.616667       34.383333
         namo_ndr      50.0          32.516667       17.483333
         snamo         50.0          42.719298        7.280702
         snamo_ncr     50.0          12.859649       37.140351
         snamo_ndr     50.0          30.228070       19.771930
4        namo          50.0          39.862500       10.137500
         namo_ncr      50.0          10.325000       39.675000
         namo_ndr      50.0          23.275000       26.725000
         snamo         50.0          35.712500       14.287500
         snamo_ncr     50.0           9.250000       40.750000
         snamo_ndr     50.0          25.525000       24.475000
5        namo          50.0          35.630000       14.370000
         namo_ncr      50.0           7.990000       42.010000
         namo_ndr      50.0          17.960000       32.040000
         snamo         50.0          31.860000       18.140000
         snamo_ncr     50.0           8.010000       41.990000
         snamo_ndr     50.0          18.620000       31.380000
6        namo          50.0          32.983333       17.016667
         namo_ncr      50.0           7.216667       42.783333
         namo_ndr      50.0          15.275000       34.725000
         snamo         50.0          27.150000       22.850000
         snamo_ncr     50.0           6.008333       43.991667
         snamo_ndr     50.0          17.000000       33.000000
7        namo          50.0          26.548872       23.451128
         namo_ncr      50.0           5.500000       44.500000
         namo_ndr      50.0          11.628571       38.371429
         snamo         50.0          20.957143       29.042857
         snamo_ncr     50.0           4.992857       45.007143
         snamo_ndr     50.0          12.030075       37.969925

                    distance_traveled  n_transfers  planning_time  \
n_robots algorithm
1        namo            36406.636951    23.500000      14.321596
         namo_ncr        36406.636951    23.500000      14.387199
         namo_ndr        36406.636951    23.500000      14.336039
         snamo           30149.375172    16.650000      60.574144
         snamo_ncr       30149.375172    16.650000      61.156751
         snamo_ndr       30149.375172    16.650000      61.437592
2        namo            47740.058247    24.925000      43.371363
         namo_ncr        15017.302407    10.675000      15.132012
         namo_ndr        24824.808234    19.250000      33.043488
         snamo           32489.441393    14.825000     152.467768
         snamo_ncr       12880.946488     7.875000      80.233354
         snamo_ndr       23777.117319    13.575000     127.907554
3        namo            56446.101036    23.649123      83.478663
         namo_ncr         9196.181915     7.266667      16.736087
         namo_ndr        26035.158288    16.733333      41.836850
         snamo           31844.374274    12.175439     316.565561
         snamo_ncr        7813.355403     4.561404     104.411128
         snamo_ndr       20226.672585     9.561404     143.339267
4        namo            55373.163335    20.700000     103.266044
         namo_ncr         6282.539647     4.650000      16.685325
         namo_ndr        20550.274851    11.812500      52.856590
         snamo           28480.969302    10.062500     226.021832
         snamo_ncr        5360.725188     3.187500     117.901739
         snamo_ndr       17624.393501     8.187500     177.096307
5        namo            56142.611196    17.950000     140.531292
         namo_ncr         4578.478592     3.420000      15.939155
         namo_ndr        18110.845453     9.690000      63.757406
         snamo           30486.084378     8.460000     263.439525
         snamo_ncr        4469.770768     2.780000     120.409844
         snamo_ndr       13520.449403     5.470000     198.540119
6        namo            57866.726891    17.758333     165.508485
         namo_ncr         3885.945770     3.191667      16.884565
         namo_ndr        15519.177847     8.666667      63.285183
         snamo           28825.815800     7.583333     304.217610
         snamo_ncr        3258.633875     2.075000     102.062642
         snamo_ndr       12472.986092     4.771930     179.181445
7        namo            53016.726541    13.661654     188.581110
         namo_ncr         2801.612258     2.628571      18.239701
         namo_ndr        12442.280173     6.371429      59.808194
         snamo           24188.240407     6.042857     318.165761
         snamo_ncr        2666.772744     1.707143     114.992147
         snamo_ndr        9449.995879     3.601504     223.419038

                    n_planning_timeouts  postponements     replans  \
n_robots algorithm
1        namo                  0.000000       0.000000   50.000000
         namo_ncr              0.000000       0.000000   50.000000
         namo_ndr              0.000000       0.000000   50.000000
         snamo                 0.000000       0.000000   50.000000
         snamo_ncr             0.000000       0.000000   50.000000
         snamo_ndr             0.000000       0.000000   50.000000
2        namo                  0.050000     464.600000  107.050000
         namo_ncr              0.000000       0.000000   50.000000
         namo_ndr              0.075000     282.700000   69.750000
         snamo                 0.125000     523.675000  114.200000
         snamo_ncr             0.000000       0.000000   50.000000
         snamo_ndr             0.025000     323.775000   71.425000
3        namo                  0.157895     794.561404  157.421053
         namo_ncr              0.000000       0.000000   50.000000
         namo_ndr              0.050000     443.100000   82.183333
         snamo                 0.052632     891.140351  146.421053
         snamo_ncr             0.035088       0.000000   49.964912
         snamo_ndr             0.105263     469.175439   81.719298
4        namo                  0.087500    1160.687500  185.100000
         namo_ncr              0.000000       0.000000   50.000000
         namo_ndr              0.100000     538.612500   87.937500
         snamo                 0.137500    1219.025000  185.875000
         snamo_ncr             0.037500       0.000000   49.962500
         snamo_ndr             0.125000     540.000000   87.025000
5        namo                  0.340000    1517.900000  220.350000
         namo_ncr              0.000000       0.000000   50.000000
         namo_ndr              0.110000     617.980000   96.080000
         snamo                 0.180000    1479.460000  219.780000
         snamo_ncr             0.030000       0.000000   49.970000
         snamo_ndr             0.230000     527.240000   87.200000
6        namo                  0.058333    1983.416667  274.041667
         namo_ncr              0.008333       0.000000   49.991667
         namo_ndr              0.075000     611.041667   95.741667
         snamo                 0.233333    1659.500000  245.508333
         snamo_ncr             0.008333       0.000000   49.991667
         snamo_ndr             0.087719     533.903509   87.377193
7        namo                  0.067669    2398.255639  320.225564
         namo_ncr              0.007143       0.000000   49.992857
         namo_ndr              0.028571     624.228571   96.885714
         snamo                 0.114286    1758.878571  244.478571
         snamo_ncr             0.057143       0.000000   49.942857
         snamo_ndr             0.210526     518.819549   87.218045

                    transfer_distance_traveled  n_conflicts  n_rr_conflicts  \
n_robots algorithm
1        namo                      1374.510304     0.000000        0.000000
         namo_ncr                  1374.510304     0.000000        0.000000
         namo_ndr                  1374.510304     0.000000        0.000000
         snamo                     3380.949854     0.000000        0.000000
         snamo_ncr                 3380.949854     0.000000        0.000000
         snamo_ndr                 3380.949854     0.000000        0.000000
2        namo                      1579.644451   895.625000      890.200000
         namo_ncr                   682.825957    26.975000       25.950000
         namo_ndr                  1270.414846   293.925000      288.225000
         snamo                     3688.735756   875.275000      869.375000
         snamo_ncr                 1954.641296    27.375000       26.700000
         snamo_ndr                 3526.624580   333.275000      327.975000
3        namo                      1443.887944  1323.491228     1315.263158
         namo_ncr                   486.356392    33.566667       33.083333
         namo_ndr                  1111.571174   459.183333      452.866667
         snamo                     2963.652230  1563.070175     1555.912281
         snamo_ncr                 1189.058807    36.192982       35.526316
         snamo_ndr                 2455.151278   487.035088      480.754386
4        namo                      1266.253497  1883.512500     1871.612500
         namo_ncr                   325.452061    38.975000       38.125000
         namo_ndr                   780.094303   563.462500      556.087500
         snamo                     2423.145370  2828.162500     2819.462500
         snamo_ncr                  819.202560    39.987500       39.387500
         snamo_ndr                 1946.948276   562.400000      554.100000
5        namo                      1132.887680  2483.180000     2471.060000
         namo_ncr                   246.859819    41.270000       40.580000
         namo_ndr                   622.168083   648.160000      640.100000
         snamo                     1947.425842  3317.850000     3309.280000
         snamo_ncr                  673.280425    41.170000       40.570000
         snamo_ndr                 1386.195417   555.760000      548.650000
6        namo                      1035.637932  3182.291667     3170.691667
         namo_ncr                   223.942914    42.058333       41.258333
         namo_ndr                   580.003102   643.566667      636.525000
         snamo                     1618.147130  3897.333333     3890.700000
         snamo_ncr                  492.061817    43.233333       42.483333
         snamo_ndr                 1234.536099   565.175439      558.640351
7        namo                       846.771471  3733.127820     3721.157895
         namo_ncr                   186.811366    43.892857       43.078571
         namo_ndr                   435.845654   661.057143      654.550000
         snamo                     1429.634267  5348.885714     5342.671429
         snamo_ncr                  347.808242    44.392857       43.771429
         snamo_ndr                  836.266197   554.909774      548.593985

                        n_steps
n_robots algorithm
1        namo       2917.400000
         namo_ncr   2917.400000
         namo_ndr   2917.400000
         snamo      2434.650000
         snamo_ncr  2434.650000
         snamo_ndr  2434.650000
2        namo       4700.475000
         namo_ncr   1257.650000
         namo_ndr   2348.125000
         snamo      3878.275000
         snamo_ncr  1081.075000
         snamo_ndr  2266.750000
3        namo       5782.385965
         namo_ncr    805.300000
         namo_ndr   2583.300000
         snamo      4467.315789
         snamo_ncr   680.245614
         snamo_ndr  2120.263158
4        namo       6264.500000
         namo_ncr    566.412500
         namo_ndr   2242.800000
         snamo      5534.250000
         snamo_ncr   486.550000
         snamo_ndr  1990.912500
5        namo       6901.720000
         namo_ncr    432.700000
         namo_ndr   2118.420000
         snamo      6291.490000
         snamo_ncr   417.390000
         snamo_ndr  1650.150000
6        namo       7746.941667
         namo_ncr    376.383333
         namo_ndr   1908.575000
         snamo      6764.683333
         snamo_ncr   319.975000
         snamo_ndr  1576.947368
7        namo       7913.984962
         namo_ncr    291.185714
         namo_ndr   1683.078571
         snamo      7750.835714
         snamo_ncr   272.528571
         snamo_ndr  1326.263158

In [65]:
std = data.groupby(['n_robots','algorithm']).std()
std

                    n_goals  n_goals_completed  n_goals_failed  \
n_robots algorithm
1        namo           0.0           0.688247        0.688247
         namo_ncr       0.0           0.688247        0.688247
         namo_ndr       0.0           0.688247        0.688247
         snamo          0.0           1.050063        1.050063
         snamo_ncr      0.0           1.050063        1.050063
         snamo_ndr      0.0           1.050063        1.050063
2        namo           0.0           8.104723        8.104723
         namo_ncr       0.0           8.183630        8.183630
         namo_ndr       0.0           7.266184        7.266184
         snamo          0.0           3.213653        3.213653
         snamo_ncr      0.0           6.476734        6.476734
         snamo_ndr      0.0           7.200027        7.200027
3        namo           0.0           6.855655        6.855655
         namo_ncr       0.0           9.918467        9.918467
         namo_ndr       0.0           4.774550        4.774550
         snamo          0.0           3.529237        3.529237
         snamo_ncr      0.0          11.285956       11.285956
         snamo_ndr      0.0           6.088683        6.088683
4        namo           0.0           7.081342        7.081342
         namo_ncr       0.0           7.766815        7.766815
         namo_ndr       0.0           7.719735        7.719735
         snamo          0.0          10.786998       10.786998
         snamo_ncr      0.0           9.448729        9.448729
         snamo_ndr      0.0           6.657964        6.657964
5        namo           0.0           6.622055        6.622055
         namo_ncr       0.0           6.532738        6.532738
         namo_ndr       0.0           6.785189        6.785189
         snamo          0.0          10.956314       10.956314
         snamo_ncr      0.0           7.658751        7.658751
         snamo_ndr      0.0           7.765216        7.765216
6        namo           0.0           5.768625        5.768625
         namo_ncr       0.0           5.949625        5.949625
         namo_ndr       0.0           6.340430        6.340430
         snamo          0.0          11.465439       11.465439
         snamo_ncr      0.0           5.854677        5.854677
         snamo_ndr      0.0           7.329176        7.329176
7        namo           0.0           6.481286        6.481286
         namo_ncr       0.0           5.065755        5.065755
         namo_ndr       0.0           5.805409        5.805409
         snamo          0.0          13.164084       13.164084
         snamo_ncr      0.0           5.909992        5.909992
         snamo_ndr      0.0           6.964129        6.964129

                    distance_traveled  n_transfers  planning_time  \
n_robots algorithm
1        namo             8672.318785     3.804430       2.272070
         namo_ncr         8672.318785     3.804430       2.305351
         namo_ndr         8672.318785     3.804430       2.333288
         snamo            4188.874301     2.058998      24.126450
         snamo_ncr        4188.874301     2.058998      23.755188
         snamo_ndr        4188.874301     2.058998      24.384312
2        namo            29642.869299     5.516351      17.406562
         namo_ncr         6249.061466     3.682164       3.021101
         namo_ndr         5624.306357     5.122850      17.602652
         snamo           10002.205767     2.668789      89.152081
         snamo_ncr        4278.402171     2.709788      59.690433
         snamo_ndr        4429.375789     3.388423      88.095594
3        namo            31230.710397     5.235494      43.150293
         namo_ncr         6790.913834     4.479205       5.223097
         namo_ndr         7460.647291     4.528129      16.942632
         snamo            6023.295069     2.897800     285.575941
         snamo_ncr        6696.607448     3.289689      91.990217
         snamo_ndr        4244.557887     2.751737      77.411502
4        namo            27620.894778     5.380226      44.510476
         namo_ncr         5471.243926     3.884732       5.109394
         namo_ndr         7711.668654     4.444008      37.760954
         snamo            8890.967689     3.943730     101.626984
         snamo_ncr        5370.998583     3.214263      90.980609
         snamo_ndr        4239.004756     2.934275     102.272643
5        namo            27835.963634     5.347283      72.138799
         namo_ncr         3916.239315     2.910031       6.127784
         namo_ndr         7598.422784     4.155306      48.423832
         snamo           14008.209013     3.901360     130.276012
         snamo_ncr        4357.086541     2.649871      89.887385
         snamo_ndr        5063.146515     2.837181     126.409465
6        namo            29625.012965     5.326319      56.750523
         namo_ncr         3657.793435     3.231400       7.322341
         namo_ndr         7989.380852     3.735664      36.562321
         snamo           13045.184398     4.113073     137.518287
         snamo_ncr        3193.497377     2.000683      69.511907
         snamo_ndr        5090.003105     2.583251     110.257381
7        namo            24198.083219     5.278440      56.934760
         namo_ncr         2752.280781     2.919404       8.222806
         namo_ndr         5647.188564     3.571153      20.409639
         snamo           14498.006654     4.279567     176.321241
         snamo_ncr        2851.609103     1.913588      79.825755
         snamo_ndr        4328.603966     2.003557     166.233966

                    n_planning_timeouts  postponements    replans  \
n_robots algorithm
1        namo                  0.000000       0.000000   0.000000
         namo_ncr              0.000000       0.000000   0.000000
         namo_ndr              0.000000       0.000000   0.000000
         snamo                 0.000000       0.000000   0.000000
         snamo_ncr             0.000000       0.000000   0.000000
         snamo_ndr             0.000000       0.000000   0.000000
2        namo                  0.220721     184.984934  35.283431
         namo_ncr              0.000000       0.000000   0.000000
         namo_ndr              0.266747      92.366661   7.062904
         snamo                 0.334932     181.746003  33.336820
         snamo_ncr             0.000000       0.000000   0.000000
         snamo_ndr             0.158114     101.331517   7.309592
3        namo                  0.413585     210.103292  68.502072
         namo_ncr              0.000000       0.000000   0.000000
         namo_ndr              0.219784     127.095547  10.009304
         snamo                 0.225282     235.176411  35.110513
         snamo_ncr             0.185637       0.000000   0.185637
         snamo_ndr             0.309620     128.567537   8.626691
4        namo                  0.325839     300.958242  52.878078
         namo_ncr              0.000000       0.000000   0.000000
         namo_ndr              0.607964     169.013256  12.761040
         snamo                 0.470490     351.403046  54.146163
         snamo_ncr             0.335410       0.000000   0.335410
         snamo_ndr             0.368885     146.516254  10.338542
5        namo                  0.831452     297.143760  54.659714
         namo_ncr              0.000000       0.000000   0.000000
         namo_ndr              0.510397     174.197379  14.286166
         snamo                 0.500101     379.090123  73.402802
         snamo_ncr             0.171447       0.000000   0.171447
         snamo_ndr             0.509605     159.593810  12.722366
6        namo                  0.268698     362.440342  62.331102
         namo_ncr              0.091287       0.000000   0.091287
         namo_ndr              0.413278     190.089956  14.485284
         snamo                 0.604372     468.901828  79.320327
         snamo_ncr             0.091287       0.000000   0.091287
         snamo_ndr             0.389268     177.670121  13.738642
7        namo                  0.330186     442.301773  66.956750
         namo_ncr              0.084515       0.000000   0.084515
         namo_ndr              0.167197     179.060230  14.438202
         snamo                 0.380944     533.189365  94.488435
         snamo_ncr             0.374961       0.000000   0.374961
         snamo_ndr             0.551206     176.974910  13.673874

                    transfer_distance_traveled  n_conflicts  n_rr_conflicts  \
n_robots algorithm
1        namo                       181.370559     0.000000        0.000000
         namo_ncr                   181.370559     0.000000        0.000000
         namo_ndr                   181.370559     0.000000        0.000000
         snamo                      580.917831     0.000000        0.000000
         snamo_ncr                  580.917831     0.000000        0.000000
         snamo_ndr                  580.917831     0.000000        0.000000
2        namo                       356.739571  1250.429438     1250.830600
         namo_ncr                   239.282982     8.175911        8.439680
         namo_ndr                   386.517441    94.791914       92.536199
         snamo                     1159.939304   532.340694      532.912014
         snamo_ncr                  865.927131     6.915933        6.962169
         snamo_ndr                 1151.400893   102.123100      101.228983
3        namo                       389.373619   739.114386      738.646772
         namo_ncr                   305.225038    10.279759       10.131829
         namo_ndr                   347.645672   128.327638      125.465704
         snamo                      868.071954   684.106818      683.048479
         snamo_ncr                  978.823859    11.653385       11.669719
         snamo_ndr                  961.245344   128.977568      126.597687
4        namo                       383.017479  1190.908131     1190.951832
         namo_ncr                   265.287383     7.890027        7.987926
         namo_ndr                   304.653805   167.597691      166.150016
         snamo                     1135.820202  2414.253002     2414.461420
         snamo_ncr                  896.096962     9.502157        9.428604
         snamo_ndr                  860.218420   146.695465      146.783023
5        namo                       414.652879   929.406125      930.549765
         namo_ncr                   195.615633     6.711749        6.793015
         namo_ndr                   256.502145   173.307091      171.644718
         snamo                     1208.714908  2584.071118     2585.123025
         snamo_ncr                  764.081541     8.059194        8.149184
         snamo_ndr                  813.826572   159.213415      158.083815
6        namo                       345.196115  1051.452108     1052.961991
         namo_ncr                   225.528815     6.159362        6.400493
         namo_ndr                   297.325338   189.388788      188.305579
         snamo                      943.044824  2549.450329     2551.190576
         snamo_ncr                  528.931982     5.977174        6.135697
         snamo_ndr                  840.579097   175.236641      173.401479
7        namo                       356.119645   893.485373      891.865714
         namo_ncr                   203.830237     5.243285        5.516578
         namo_ndr                   259.994122   178.306775      176.623582
         snamo                     1129.192592  3247.912204     3249.916923
         snamo_ncr                  404.849836     5.846596        5.937738
         snamo_ndr                  615.127198   174.445462      174.155583

                        n_steps
n_robots algorithm
1        namo        613.734933
         namo_ncr    613.734933
         namo_ndr    613.734933
         snamo       298.927781
         snamo_ncr   298.927781
         snamo_ndr   298.927781
2        namo       2290.662450
         namo_ncr    478.084080
         namo_ndr    465.099118
         snamo      1386.076551
         snamo_ncr   325.753988
         snamo_ndr   406.275942
3        namo       2442.517991
         namo_ncr    537.189557
         namo_ndr    617.076055
         snamo      1137.970800
         snamo_ncr   522.034833
         snamo_ndr   381.082177
4        namo       2252.858190
         namo_ncr    429.103354
         namo_ndr    715.004707
         snamo      1965.482590
         snamo_ncr   427.108645
         snamo_ndr   412.722274
5        namo       2286.149381
         namo_ncr    314.818386
         namo_ndr    713.603874
         snamo      2110.429893
         snamo_ncr   344.641283
         snamo_ndr   485.166833
6        namo       2510.915439
         namo_ncr    292.054018
         namo_ndr    764.444025
         snamo      2093.629059
         snamo_ncr   252.967280
         snamo_ndr   527.131020
7        namo       2060.006351
         namo_ncr    225.135693
         namo_ndr    572.801811
         snamo      2257.625125
         snamo_ncr   230.050837
         snamo_ndr   475.405981

In [73]:
avg.loc[[(3,"namo"), (3, "snamo")]]

                    n_goals  n_goals_completed  n_goals_failed  \
n_robots algorithm
3        namo          50.0          42.000000        8.000000
         snamo         50.0          42.719298        7.280702

                    distance_traveled  n_transfers  planning_time  \
n_robots algorithm
3        namo            56446.101036    23.649123      83.478663
         snamo           31844.374274    12.175439     316.565561

                    n_planning_timeouts  postponements     replans  \
n_robots algorithm
3        namo                  0.157895     794.561404  157.421053
         snamo                 0.052632     891.140351  146.421053

                    transfer_distance_traveled  n_conflicts  n_rr_conflicts  \
n_robots algorithm
3        namo                      1443.887944  1323.491228     1315.263158
         snamo                     2963.652230  1563.070175     1555.912281

                        n_steps
n_robots algorithm
3        namo       5782.385965
         snamo      4467.315789

In [67]:
std.loc[[(3,"namo"), (3, "snamo")]]

                    n_goals  n_goals_completed  n_goals_failed  \
n_robots algorithm
3        namo           0.0           6.855655        6.855655
         snamo          0.0           3.529237        3.529237

                    distance_traveled  n_transfers  planning_time  \
n_robots algorithm
3        namo            31230.710397     5.235494      43.150293
         snamo            6023.295069     2.897800     285.575941

                    n_planning_timeouts  postponements    replans  \
n_robots algorithm
3        namo                  0.413585     210.103292  68.502072
         snamo                 0.225282     235.176411  35.110513

                    transfer_distance_traveled  n_conflicts  n_rr_conflicts  \
n_robots algorithm
3        namo                       389.373619   739.114386      738.646772
         snamo                      868.071954   684.106818      683.048479

                        n_steps
n_robots algorithm
3        namo       2442.517991
         snamo      1137.970800